[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "neuroreader"
description = "Utility to read and parse .nev, .nsx, and .nfx files used in neural recordings"
readme = "README.md"
requires-python = ">=3.13"
license = { file = "LICENSE" }
authors = [{ name = "Raj Magesh Gauthaman", email = "neuroreader@raj-magesh.org" }]
keywords = [
    "neural recording",
    "parser",
    ".nev",
    ".nsx",
    ".nfx",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
urls = { repository = "https://codeberg.org/raj-magesh/neuroreader" }
dependencies = [
    "numpy",
    "pint",
    "pandas",
    "pint-pandas",
    "xarray",
    "edfio",
]
version = "0.1.0"  # FIXME(dynamic version): https://github.com/astral-sh/uv/issues/8714

[dependency-groups]
dev = [
    "ruff",
    "pytest",
    "sphinx",
]

[tool.uv]
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
